import assert from "node:assert/strict";
import { createInitialAgents } from "../src/agents.js";
import { createSimulation } from "../src/simulation.js";
import { discoverArea, rememberAreaVisit } from "../src/exploration.js";
import { world } from "../src/world.js";
const sim = createSimulation(structuredClone(world), [createInitialAgents()[0]]);
const agent = sim.agents[0];
const first = discoverArea(sim, agent);
assert(first.id.startsWith("area-"));
assert.equal(sim.world.exploration.discoveredAreas.length, 1);
rememberAreaVisit(sim, agent, first);
assert(agent.exploredAreas.includes(first.id));
const second = discoverArea(sim, agent);
assert.equal(second.id, first.id);
assert.equal(sim.world.exploration.discoveredAreas.length, 1);
agent.position = { x: 30, z: -30 };
const third = discoverArea(sim, agent);
assert.notEqual(third.id, first.id);
assert.equal(sim.world.exploration.discoveredAreas.length, 2);
console.log("Lúmina exploration audit: territorio persistente verificado.");
