import assert from "node:assert/strict";
import { getRegionKey, updateSettlementState } from "../src/spatial.js";
import { world as baseWorld } from "../src/world.js";
const world=structuredClone(baseWorld);
world.structures={shelters:[{id:"s1",position:{x:0,z:0}}],farms:[]};
const agents=[{id:"a",alive:true,position:{x:0,z:0}}];
updateSettlementState(world,agents);
const key=getRegionKey({x:0,z:0},world);
const state=world.spatial.regions[key];
assert.equal(state.population,1);
assert.equal(state.structures,1);
assert.ok(state.settlementLevel>=1);
assert.ok(state.activity>0);
console.log(JSON.stringify({audit:"settlement-state",region:key,level:state.settlementLevel,verdict:"PASS"},null,2));
