// Producción emergente: herramientas y cultivos aparecen como posibilidades que deben descubrirse.
export const TOOL_COST = Object.freeze({ wood: 5, stone: 3 });
export const FARM_COST = Object.freeze({ wood: 4 });
export function amount(agent,type){return (agent.inventory??[]).reduce((s,i)=>i.type===type?s+(Number(i.amount)||0):s,0);}
export function consume(agent,type,n){let r=n;for(const i of agent.inventory??[]){if(i.type!==type||r<=0)continue;const u=Math.min(Number(i.amount)||0,r);i.amount-=u;r-=u;}agent.inventory=(agent.inventory??[]).filter(i=>(Number(i.amount)||0)>0);return r<=1e-9;}
export function canCraftTool(agent){return amount(agent,"wood")>=TOOL_COST.wood&&amount(agent,"stone")>=TOOL_COST.stone;}
export function craftTool(agent){if(!canCraftTool(agent))return{success:false,reason:"insufficient_materials"};consume(agent,"wood",TOOL_COST.wood);consume(agent,"stone",TOOL_COST.stone);const existing=agent.skills.find(s=>s.name==="toolmaking");if(existing)existing.level=Math.min(1,existing.level+.12);else agent.skills.push({name:"toolmaking",level:.12,learnedOnDay:null});return{success:true,effect:"tool_crafted"};}
export function canFarm(agent){return amount(agent,"wood")>=FARM_COST.wood;}
export function farm(simulation,agent){if(!canFarm(agent))return{success:false,reason:"insufficient_materials"};const land=simulation.world.resources.fertile_land;if(land.amount<5)return{success:false,reason:"no_fertile_land"};consume(agent,"wood",FARM_COST.wood);land.amount-=5;simulation.world.structures??={shelters:[],farms:[]};const id=`farm-${simulation.world.structures.farms.length+1}`;simulation.world.structures.farms.push({id,type:"farm",ownerId:agent.id,position:{...agent.position},builtOnDay:simulation.day,food:0,health:100});agent.needs.safety=Math.min(100,agent.needs.safety+5);return{success:true,effect:"farm_created",structureId:id};}
export function advanceProductionDay(targetWorld){const farms=targetWorld.structures?.farms??[];const land=targetWorld.resources?.fertile_land;if(!land)return;for(const farm of farms){if(farm.health<=0)continue;const yieldAmount=Math.max(0,1.5*land.quality);farm.food=Math.min(100,farm.food+yieldAmount);land.quality=Math.max(.2,land.quality-.003);}}
