// Producción emergente: herramientas y cultivos aparecen como posibilidades que deben descubrirse.
export const TOOL_COST = Object.freeze({ wood: 5, stone: 3 });
export const FARM_COST = Object.freeze({ wood: 4 });
export const TOOL_MAX_DURABILITY = 20;
export function amount(agent,type){return (agent.inventory??[]).reduce((s,i)=>i.type===type?s+(Number(i.amount)||0):s,0);}
export function consume(agent,type,n){let r=n;for(const i of agent.inventory??[]){if(i.type!==type||r<=0)continue;const u=Math.min(Number(i.amount)||0,r);i.amount-=u;r-=u;}agent.inventory=(agent.inventory??[]).filter(i=>(Number(i.amount)||0)>0);return r<=1e-9;}
export function canCraftTool(agent){return amount(agent,"wood")>=TOOL_COST.wood&&amount(agent,"stone")>=TOOL_COST.stone;}
export function craftTool(agent, targetWorld = null){if(!canCraftTool(agent))return{success:false,reason:"insufficient_materials"};consume(agent,"wood",TOOL_COST.wood);consume(agent,"stone",TOOL_COST.stone);const existing=agent.skills.find(s=>s.name==="toolmaking");if(existing)existing.level=Math.min(1,existing.level+.12);else agent.skills.push({name:"toolmaking",level:.12,learnedOnDay:null});const skill=agent.skills.find(s=>s.name==="toolmaking")?.level??0;const techLevel=Number(targetWorld?.technology?.levels?.tools??0);const efficiency=1+(skill>=.7?.15:0)+techLevel*.08;const durability=(skill>=.7?30:TOOL_MAX_DURABILITY)*(1+techLevel*.2);agent.inventory.push({type:"tool",kind:skill>=.7||techLevel>=1?"reinforced_hand_tool":"hand_tool",durability,efficiency});return{success:true,effect:"tool_crafted",durability,efficiency};}
export function canFarm(agent){return amount(agent,"wood")>=FARM_COST.wood;}
export function farm(simulation,agent){if(!canFarm(agent))return{success:false,reason:"insufficient_materials"};const land=simulation.world.resources.fertile_land;if(land.amount<5)return{success:false,reason:"no_fertile_land"};consume(agent,"wood",FARM_COST.wood);land.amount-=5;simulation.world.structures??={shelters:[],farms:[]};const id=`farm-${simulation.world.structures.farms.length+1}`;simulation.world.structures.farms.push({id,type:"farm",ownerId:agent.id,position:{...agent.position},builtOnDay:simulation.day,food:0,health:100});agent.farm=id;agent.needs.safety=Math.min(100,agent.needs.safety+5);return{success:true,effect:"farm_created",structureId:id};}
export function harvest(simulation,agent){const farm=simulation.world.structures?.farms?.find(f=>f.ownerId===agent.id&&f.food>0);if(!farm)return{success:false,reason:"no_ready_crop"};const food=Math.min(8,farm.food);farm.food-=food;agent.inventory.push({type:"farm_food",amount:food});return{success:true,effect:"farm_harvested",amount:food};}

export function advanceProductionDay(targetWorld){const farms=targetWorld.structures?.farms??[];const land=targetWorld.resources?.fertile_land;if(!land)return;for(const farm of farms){if(farm.health<=0)continue;const techYield=1+(Number(targetWorld.technology?.levels?.agriculture??0)*.12);const yieldAmount=Math.max(0,1.5*land.quality*techYield);farm.food=Math.min(100,farm.food+yieldAmount);land.quality=Math.max(.2,land.quality-.003);}}

export function getBestTool(agent){ return (agent.inventory??[]).filter(item=>item.type==="tool" && Number(item.durability)>0).sort((a,b)=>(Number(b.efficiency)||1)-(Number(a.efficiency)||1))[0] ?? null; }
export function useTool(agent){ const tool=getBestTool(agent); if(!tool) return null; tool.durability=Math.max(0,Number(tool.durability)-1); agent.inventory=(agent.inventory??[]).filter(item=>item.type!=="tool" || Number(item.durability)>0); return { kind: tool.kind, durability: Number(tool.durability), efficiency: Number(tool.efficiency)||1 }; }
