// Investigación y experimentación de Lúmina.
const MAX_TOPICS=80,MAX_EXPERIMENTS=600,MAX_EVIDENCE=120;
const DEFINITIONS={gatherer:{id:"resource-regeneration",domain:"ecology",question:"¿La presión sobre un recurso afecta su recuperación?",variable:"humanPressure",measure:"regeneration",hypothesis:"Una presión humana mayor reduce la recuperación de recursos."},farmer:{id:"soil-yield",domain:"agriculture",question:"¿La calidad del suelo cambia de forma medible el rendimiento?",variable:"soilQuality",measure:"farmYield",hypothesis:"Un suelo de mayor calidad produce más alimento."},builder:{id:"shelter-durability",domain:"construction",question:"¿La experiencia de construcción aumenta la resistencia?",variable:"buildSkill",measure:"shelterDurability",hypothesis:"Una mayor experiencia produce refugios más resistentes."},craftsperson:{id:"tool-durability",domain:"tools",question:"¿La habilidad de fabricación prolonga la vida de una herramienta?",variable:"toolSkill",measure:"toolDurability",hypothesis:"Una mayor habilidad produce herramientas más duraderas."},trader:{id:"scarcity-price",domain:"economy",question:"¿La escasez relativa cambia el precio?",variable:"stockPerCapita",measure:"price",hypothesis:"Una menor disponibilidad relativa aumenta el precio."}};
export function normalizeResearchWorld(world){world.research??={topics:[],experiments:[],evidence:[],history:[]};const r=world.research;r.topics??=[];r.experiments??=[];r.evidence??=[];r.history??=[];for(const t of r.topics){t.contributors??=[];t.experimentCount??=0;t.supportedCount??=0;t.contradictedCount??=0;t.independentReplications??=0;t.confidence=clamp(Number(t.confidence??.1),0,.95);}return r;}
export function normalizeResearchAgent(agent){agent.researchKnowledge??=[];agent.researchExperiments??=0;return agent.researchKnowledge;}
export function getResearchTopics(agent,world){normalizeResearchAgent(agent);const role=agent.specialization?.role;let d=DEFINITIONS[role];if(!d){const known=new Set((agent.knowledge??[]).map(k=>String(k.topic??"").replace(/^action:/,"")));const skills=new Set((agent.skills??[]).map(s=>s.name));if(known.has("farm")||skills.has("farm"))d=DEFINITIONS.farmer;else if(known.has("build_shelter")||skills.has("build_shelter"))d=DEFINITIONS.builder;else if(known.has("craft_tool")||skills.has("craft_tool")||skills.has("toolmaking"))d=DEFINITIONS.craftsperson;else if(known.has("trade")||skills.has("trade"))d=DEFINITIONS.trader;else d=DEFINITIONS.gatherer;}return relevant(d,world)?[d]:[];}
export function advanceResearchDay(simulation){const r=normalizeResearchWorld(simulation.world);const alive=simulation.agents.filter(a=>a?.alive);const contributors=new Set();for(const agent of alive){normalizeResearchAgent(agent);const d=getResearchTopics(agent,simulation.world)[0];if(!d)continue;const topic=getOrCreateTopic(r,d,simulation.day);const result=runResearchExperiment(simulation,agent,topic);if(!result)continue;topic.experimentCount++;topic.lastExperimentDay=simulation.day;if(result.record.supported)topic.supportedCount++;else topic.contradictedCount++;if(r.experiments.some(e=>e.topicId===topic.id&&e.agentId!==agent.id))topic.independentReplications++;if(!topic.contributors.includes(agent.id))topic.contributors.push(agent.id);r.experiments.push(result.experiment);r.evidence.push(result.record);contributors.add(agent.id);updateConfidence(topic);updateAgentKnowledge(agent,topic,result.record);agent.researchExperiments++;simulation.events.push({id:`research-event-${simulation.events.length}`,day:simulation.day,hour:0,type:"research_experiment",description:`${agent.name} realizó un experimento sobre ${topic.id}.`,participants:[agent.id]});}if(contributors.size)r.history.push({day:simulation.day,type:"research_day",contributors:[...contributors]});r.history=r.history.slice(-300);r.experiments=r.experiments.slice(-MAX_EXPERIMENTS);r.evidence=r.evidence.slice(-MAX_EVIDENCE);r.topics=r.topics.slice(-MAX_TOPICS);}
export function runResearchExperiment(simulation,agent,topic){const before=measure(simulation,agent,topic);if(before==null)return null;const factor=(topic.id==="resource-regeneration"||topic.id==="scarcity-price")?.9:1.1;const after=topic.id==="resource-regeneration"?Math.max(0,1-Math.min(1,Number(simulation.world.ecosystem?.humanPressure??0)*(2-factor))):before*factor;const delta=after-before;const negative=topic.id==="resource-regeneration"||topic.id==="scarcity-price";const supported=negative?delta<-.0001:delta>.0001;const id=`experiment-${simulation.day}-${agent.id}-${topic.id}`;const record={id:id+"-evidence",experimentId:id,day:simulation.day,topicId:topic.id,agentId:agent.id,variable:topic.variable,baseline:round(before),intervention:"comparación controlada",result:round(after),delta:round(delta),supported,reliability:.65};return{record,experiment:{id,day:simulation.day,topicId:topic.id,question:topic.question,hypothesis:topic.hypothesis,agentId:agent.id,variable:topic.variable,baseline:round(before),intervention:"comparación controlada",result:round(after),supported,reproducible:false}};}
export function recordResearchEvidence(world,evidence){const r=normalizeResearchWorld(world);r.evidence.push({...evidence});r.evidence=r.evidence.slice(-MAX_EVIDENCE);const t=r.topics.find(x=>x.id===evidence.topicId);if(t){if(!t.contributors.includes(evidence.agentId))t.contributors.push(evidence.agentId);t.experimentCount++;updateConfidence(t);}return evidence;}
export function researchSummary(world){const r=normalizeResearchWorld(world);return{topics:r.topics.length,experiments:r.experiments.length,evidence:r.evidence.length,reproducedTopics:r.topics.filter(t=>t.contributors.length>=2).length,strongest:[...r.topics].sort((a,b)=>b.confidence-a.confidence).slice(0,5).map(t=>({id:t.id,confidence:t.confidence,contributors:t.contributors.length,experiments:t.experimentCount,independentReplications:t.independentReplications,supported:t.supportedCount,contradicted:t.contradictedCount}))};}
function getOrCreateTopic(r,d,day){let t=r.topics.find(x=>x.id===d.id);if(t)return t;t={id:d.id,domain:d.domain,question:d.question,hypothesis:d.hypothesis,variable:d.variable,measure:d.measure,confidence:.1,experimentCount:0,contributors:[],createdDay:day,lastExperimentDay:null,status:"open",supportedCount:0,contradictedCount:0,independentReplications:0};r.topics.push(t);return t;}
function updateConfidence(t){const people=Math.min(1,t.contributors.length/4),rep=Math.min(1,t.independentReplications/3),count=Math.min(1,t.experimentCount/8),ratio=t.experimentCount?t.supportedCount/t.experimentCount:.5;t.confidence=clamp(.08+people*.28+count*.28+Math.max(ratio,1-ratio)*.24+rep*.12,0,.95);if(t.independentReplications>=2&&t.experimentCount>=4)t.status="reproduced";else if(t.experimentCount>=2)t.status="tested";}
function updateAgentKnowledge(a,t,e){let k=a.researchKnowledge.find(x=>x.topicId===t.id);if(!k){k={topicId:t.id,belief:t.hypothesis,confidence:.1,evidenceCount:0,lastTestedDay:null};a.researchKnowledge.push(k);}k.evidenceCount++;k.lastTestedDay=e.day;k.confidence=clamp(k.confidence+(e.supported?.08:-.05)*(1-k.confidence),0,.95);a.researchKnowledge=a.researchKnowledge.slice(-24);}
function relevant(d,w){if(d.id==="scarcity-price")return!!w.economy;if(d.id==="resource-regeneration")return Object.keys(w.resources??{}).length>0;return true;}
function measure(s,a,t){if(t.id==="resource-regeneration")return Math.max(0,1-Number(s.world.ecosystem?.humanPressure??0));if(t.id==="scarcity-price")return Number(s.world.economy?.priceMemory?.farm_food??3);if(t.id==="soil-yield")return 1.5*Number(s.world.ecosystem?.soilQuality??0);if(t.id==="shelter-durability")return 20*(1+Number(a.skills?.find(x=>x.name==="build_shelter")?.level??0)*.5);if(t.id==="tool-durability")return 20*(1+Number(a.skills?.find(x=>x.name==="toolmaking")?.level??0)*.5);return null;}
function round(v){return Number(Number(v).toFixed(6));}function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
