// Motor de simulación de Lúmina.
// Coordina tiempo, necesidades, percepción, decisiones, acciones y aprendizaje.

import { perceiveWorld } from "./perception.js";
import { updateNeeds, applyNeedConsequences } from "./needs.js";
import { createDecisionContext, evaluateOptions, chooseOption } from "./decision.js";
import { advanceWorldDay } from "./world.js";
import { getKnownActions, discoverAction, updateActionBelief } from "./discovery.js";
import { executeAction } from "./actions.js";
import { remember, learnFromEvidence } from "./memory.js";
import { recordInteraction } from "./relationships.js";
import { stopMovement } from "./movement.js";
import { getRandom } from "./random.js";
import { getInventoryAmount, canBuildShelter, normalizeDevelopmentWorld } from "./development.js";
import { canCraftTool, canFarm } from "./production.js";
import { inventoryAmount, DEFAULT_PRICES } from "./economy.js";

export function createSimulation(world, agents, options = {}) {
  normalizeDevelopmentWorld(world);
  world.economy ??= { trades: [], priceMemory: {} };
  world.cooperation ??= [];
  for (const agent of agents) agent._simulationAgents = agents;
  return { world, agents, hour: Number(world.timeOfDay) || 8, day: Number(world.day) || 1, events: [], running: false, random: options.random ?? null };
}
export function recordEvent(simulation, event) { const stored={id:event.id??`event-${simulation.events.length+1}`,day:simulation.day,hour:simulation.hour,type:event.type,description:event.description,participants:event.participants??[]}; simulation.events.push(stored); return stored; }

function findTradeOption(agent, perception, world, agents) {
  const partnerInfo=[...(perception.visibleAgents??[])].sort((a,b)=>a.distance-b.distance)[0];
  const partner=agents.find(candidate=>candidate.id===partnerInfo?.id&&candidate.alive&&candidate.id!==agent.id);
  if(!partner||Number(partner.money??0)<=0)return null;
  for(const type of ["farm_food","fish","wood","stone"]){const own=inventoryAmount(agent,type);if(own<2)continue;const partnerAmount=inventoryAmount(partner,type);const partnerNeedsFood=partner.needs.hunger<65&&(type==="fish"||type==="farm_food");const partnerNeedsMaterial=type==="wood"&&!partner.home;if(partnerAmount<=0||partnerNeedsFood||partnerNeedsMaterial){const price=Number(world.economy?.priceMemory?.[type]??DEFAULT_PRICES[type]??1);return{name:"trade",partnerId:partner.id,offerType:type,amount:1,unitPrice:price,baseValue:partnerNeedsFood?.72:.42,distance:partnerInfo.distance,effects:{social:.7}};}}
  return null;
}

function generateOptions(agent, perception, world, random=Math.random){
  const knownActions=getKnownActions(agent);const options=[];options.push({name:"rest",baseValue:0,effects:{energy:1.2},distance:0});const water=perception.nearbyResources.find(resource=>resource.type==="water");if(water)options.push({name:"drink",amount:5,baseValue:.5,effects:{thirst:1.8},distance:water.distance});
  if(perception.visibleAgents.length>0){const nearest=[...perception.visibleAgents].sort((a,b)=>a.distance-b.distance)[0];options.push({name:"socialize",baseValue:.25,effects:{social:1.4},distance:nearest.distance,relationshipBonus:relationships=>{const relationship=relationships.find(item=>item.agentId===nearest.id);if(!relationship)return.15;return Math.max(-.2,relationship.affection*.25+relationship.trust*.15-relationship.tension*.2);}});if(agent.knowledge.some(item=>item.confidence>=.3))options.push({name:"share_knowledge",baseValue:.05,effects:{social:.6},distance:nearest.distance,knowledgeBonus:knowledge=>Math.min(.35,knowledge.filter(item=>item.confidence>=.3).length*.08)});const tradeOption=findTradeOption(agent,perception,world,agent._simulationAgents??[]);if(tradeOption)options.push(tradeOption);}
  if(knownActions.some(action=>action.name==="build_shelter")&&!agent.home&&canBuildShelter(agent))options.push({name:"build_shelter",baseValue:.7,effects:{safety:1.8},distance:0});if(knownActions.some(action=>action.name==="craft_tool")&&canCraftTool(agent))options.push({name:"craft_tool",baseValue:.55,effects:{energy:-.1},distance:0});if(knownActions.some(action=>action.name==="farm")&&canFarm(agent)&&!agent.farm)options.push({name:"farm",baseValue:.65,effects:{safety:.5},distance:0});if(knownActions.some(action=>action.name==="harvest")&&simulationFarmReady(world,agent))options.push({name:"harvest",baseValue:.35,effects:{hunger:1},distance:0});if(knownActions.some(action=>action.name==="eat_farm_food")&&agent.inventory?.some(i=>i.type==="farm_food"&&i.amount>0))options.push({name:"eat_farm_food",baseValue:.8,effects:{hunger:2.4},distance:0});
  for(const action of knownActions){if(["rest","drink"].includes(action.name))continue;if(action.name==="eat_fish"&&!agent.inventory.some(item=>item.type==="fish"&&item.amount>0))continue;const resourceByAction={eat_plant:"wild_plants",catch_fish:"fish",gather_wood:"wood",gather_stone:"stone"};const requiredResource=resourceByAction[action.name];if(requiredResource&&Number(world.resources?.[requiredResource]?.amount??0)<=0)continue;const option={name:action.name,baseValue:action.confidence,distance:getKnownActionDistance(action.name,perception),knowledgeBonus:knowledge=>{const item=knowledge.find(entry=>entry.topic==="action:"+action.name);return item?item.confidence*.15:0;},memoryBonus:memories=>{const relevant=memories.filter(memory=>memory.topic==="action:"+action.name);if(!relevant.length)return 0;const recent=relevant.slice(-5);const valence=recent.reduce((sum,memory)=>sum+(memory.importance??.5)*(memory.emotionalWeight??0),0);return Math.max(-.25,Math.min(.25,valence*.5));}};if(action.name==="eat_plant"){option.effects={hunger:2.2};option.amount=1;}if(action.name==="eat_fish"){option.effects={hunger:2.3};option.amount=1;}if(action.name==="catch_fish"){option.effects={hunger:1.6};option.amount=1;}options.push(option);}
  const resourceDiscovery=[["wild_plants","explore_plants","eat_plant","planta",.9,.8],["fish","explore_fishing","catch_fish","pesca",.85,.75],["wood","explore_wood","gather_wood","madera",.75,.65],["stone","explore_stone","gather_stone","piedra",.75,.65],["fertile_land","explore_farming","farm","tierra fértil",.7,.7]];for(const[resourceType,optionName,actionName,keyword,explorationValue,baseValue]of resourceDiscovery){const resource=perception.nearbyResources.find(item=>item.type===resourceType);if(!resource||knownActions.some(action=>action.name===actionName))continue;const option={name:optionName,baseValue,explorationValue,novelty:1,knowledgeTopic:"action:"+actionName,memoryKeyword:keyword,distance:resource.distance};if(resourceType==="wild_plants")option.effects={hunger:.8};if(resourceType==="fish")option.effects={hunger:.65};options.push(option);}
  if(getInventoryAmount(agent,"wood")>=5&&getInventoryAmount(agent,"stone")>=3&&!knownActions.some(a=>a.name==="craft_tool"))options.push({name:"discover_toolmaking",baseValue:.45,explorationValue:.5,novelty:1,knowledgeTopic:"action:craft_tool",distance:0});if(getInventoryAmount(agent,"wood")>=4&&!knownActions.some(a=>a.name==="farm"))options.push({name:"discover_farming",baseValue:.4,explorationValue:.5,novelty:1,knowledgeTopic:"action:farm",distance:0});const explorationTarget=createExplorationTarget(agent,world,random);const explorationDistance=Math.hypot(explorationTarget.x-agent.position.x,explorationTarget.z-agent.position.z);options.push({name:"explore_area",baseValue:.28,explorationValue:.7,novelty:.8,distance:explorationDistance,target:explorationTarget});return options;
}
function simulationFarmReady(world,agent){return(world.structures?.farms??[]).some(f=>f.ownerId===agent.id&&Number(f.food)>0);}function getKnownActionDistance(actionName,perception){if(actionName==="eat_fish")return 0;const map={drink:"water",eat_plant:"wild_plants",catch_fish:"fish",gather_wood:"wood",gather_stone:"stone"};const type=map[actionName];if(!type)return 0;return perception.nearbyResources.find(resource=>resource.type===type)?.distance??25;}function createExplorationTarget(agent,world,random=Math.random){const bounds=world?.bounds??{minX:-34,maxX:34,minZ:-34,maxZ:34};const angle=random()*Math.PI*2;const distance=4+random()*6;return{x:Math.max(bounds.minX,Math.min(bounds.maxX,agent.position.x+Math.cos(angle)*distance)),z:Math.max(bounds.minZ,Math.min(bounds.maxZ,agent.position.z+Math.sin(angle)*distance))};}
function getActionTarget(agent,actionName,perception,world,agents){if(actionName==="build_shelter")return null;if(actionName==="explore_area")return agent.currentIntent?.target??null;if(actionName==="trade"){const other=agents.find(candidate=>candidate.id===agent.currentIntent?.partnerId&&candidate.alive);return other?.position??null;}if(actionName==="drink")return world.resources.water.position;if(actionName==="gather_wood"||actionName==="explore_wood")return world.resources.wood.position;if(actionName==="gather_stone"||actionName==="explore_stone")return world.resources.stone.position;if(actionName==="eat_plant"||actionName==="explore_plants")return world.resources.wild_plants.position;if(actionName==="catch_fish"||actionName==="explore_fishing")return world.resources.fish.position;if(actionName==="socialize"||actionName==="share_knowledge"){const nearest=[...perception.visibleAgents].sort((a,b)=>a.distance-b.distance)[0];const other=agents.find(candidate=>candidate.id===nearest?.id&&candidate.alive&&candidate.id!==agent.id);return other?.position??null;}return null;}
