// Arquitectura espacial escalable de Lúmina.
export const DEFAULT_REGION_SIZE=8;
export function normalizeSpatialWorld(world){world.bounds??={minX:-34,maxX:34,minZ:-34,maxZ:34};world.spatial??={};const s=world.spatial;s.regionSize=Math.max(1,Number(s.regionSize??DEFAULT_REGION_SIZE));s.version??=1;s.activeRegionPadding=Math.max(0,Number(s.activeRegionPadding??1));s.activeRegions??=[];s.knownRegions??=[];s.regions??={};s.biomes??={};s.ecology??={};s.regionVersion??=1;s.settlementDefaults??={activity:0,structures:0,population:0};s.runtimeActive??=false;return s;}
export function getRegionKey(position,world){const s=normalizeSpatialWorld(world),size=s.regionSize;const x=Math.floor((Number(position?.x??0)-world.bounds.minX)/size),z=Math.floor((Number(position?.z??0)-world.bounds.minZ)/size);return x+":"+z;}
export function getRegionForPosition(position,world){const s=normalizeSpatialWorld(world),size=s.regionSize,key=getRegionKey(position,world),[ix,iz]=key.split(":").map(Number);return{key,x:ix,z:iz,minX:world.bounds.minX+ix*size,maxX:Math.min(world.bounds.maxX,world.bounds.minX+(ix+1)*size),minZ:world.bounds.minZ+iz*size,maxZ:Math.min(world.bounds.maxZ,world.bounds.minZ+(iz+1)*size)};}
export function getActiveRegionKeys(agents,world,padding=null){const s=normalizeSpatialWorld(world),radius=padding==null?s.activeRegionPadding:Math.max(0,Number(padding)),active=new Set();for(const agent of agents??[]){if(!agent?.alive)continue;const r=getRegionForPosition(agent.position,world);for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++)active.add((r.x+dx)+":"+(r.z+dz));}return[...active];}
export function spatialSummary(world,agents=[]){const s=normalizeSpatialWorld(world);const width=world.bounds.maxX-world.bounds.minX,depth=world.bounds.maxZ-world.bounds.minZ,columns=Math.ceil(width/s.regionSize),rows=Math.ceil(depth/s.regionSize),active=getActiveRegionKeys(agents,world);if(s.runtimeActive)s.activeRegions=active;s.runtimeActive=true;return{bounds:{...world.bounds},width,depth,regionSize:s.regionSize,totalRegions:columns*rows,activeRegions:active.length,coverageRatio:columns*rows?active.length/(columns*rows):0};}
export const BIOME_DEFINITIONS=Object.freeze({forest:{food:1.15,wood:1.35,stone:.9,water:1,movement:.95},plains:{food:1.25,wood:.8,stone:.9,water:1,movement:1.05},mountain:{food:.65,wood:.7,stone:1.45,water:.85,movement:.8},wetland:{food:1.3,wood:.95,stone:.7,water:1.4,movement:.85},arid:{food:.55,wood:.45,stone:1,water:.35,movement:1}});
export function getBiomeForRegion(region,world){normalizeSpatialWorld(world);const key=region.key??getRegionKey(region,world);if(world.spatial.biomes[key])return world.spatial.biomes[key];const hash=stableHash(key),edge=Math.min(region.x,region.z),maxEdge=Math.max(region.x,region.z);let type="plains";if((hash+edge*3)%17===0)type="mountain";else if((hash+maxEdge*5)%13===0)type="wetland";else if((hash+region.x*7+region.z*11)%11===0)type="forest";else if((hash+region.x*5+region.z*3)%19===0)type="arid";const biome={key,type,...BIOME_DEFINITIONS[type]};world.spatial.biomes[key]=biome;world.spatial.regions[key]??={key,x:region.x,z:region.z,visits:0,discovered:false,biome:type};return biome;}
export function discoverRegion(world,position){normalizeSpatialWorld(world);const region=getRegionForPosition(position,world),biome=getBiomeForRegion(region,world),state=world.spatial.regions[region.key]??={key:region.key,x:region.x,z:region.z,visits:0,discovered:false,biome:biome.type};state.x??=region.x;state.z??=region.z;state.discovered=true;state.lastDiscoveryDay=world.day??0;return{...region,biome};}
export function recordRegionVisit(world,position,day=world.day??0){const result=discoverRegion(world,position),state=world.spatial.regions[result.key];state.visits=Number(state.visits??0)+1;state.lastVisitDay=day;return result;}
function stableHash(value){let hash=2166136261;for(const char of String(value))hash=Math.imul(hash^char.charCodeAt(0),16777619);return Math.abs(hash>>>0);}
export function getRegionalEcology(world,position){normalizeSpatialWorld(world);const region=getRegionForPosition(position,world),state=world.spatial.ecology[region.key]??={key:region.key,biodiversity:1,soilQuality:1,waterQuality:1,humanPressure:0,lastUpdateDay:Number(world.day??1)};return state;}
export function updateRegionalEcology(world,resourceStates={},population=0){normalizeSpatialWorld(world);const touched=new Set();for(const resource of Object.values(resourceStates??{})){if(resource?.position)touched.add(getRegionKey(resource.position,world));}for(const key of Object.keys(world.spatial.regions))touched.add(key);for(const key of touched){const region=world.spatial.regions[key]??={key,visits:0,discovered:false};const pos={x:world.bounds.minX+Number(region.x??0)*world.spatial.regionSize+world.spatial.regionSize/2,z:world.bounds.minZ+Number(region.z??0)*world.spatial.regionSize+world.spatial.regionSize/2};const biome=getBiomeForRegion(getRegionForPosition(pos,world),world),state=world.spatial.ecology[key]??={key,biodiversity:1,soilQuality:1,waterQuality:1,humanPressure:0,lastUpdateDay:Number(world.day??1)};const local=Object.values(resourceStates??{}).filter(r=>r?.position&&getRegionKey(r.position,world)===key);const stress=local.length?local.reduce((sum,r)=>sum+Math.max(0,1-Math.max(0,Math.min(1,(Number(r.amount)||0)/Math.max(1,Number(r.capacity??r.amount??1))))),0)/local.length:0;const biomeWater=Number(biome.water??1),biomeFood=Number(biome.food??1);const pressure=Math.max(0,Math.min(1,stress+Math.max(0,population-4)*.015));state.humanPressure=Math.max(0,Math.min(1,state.humanPressure*.9+pressure*.1));const recovery=(1-state.humanPressure)*.018;state.biodiversity=Math.max(0,Math.min(1,state.biodiversity+recovery-(1-biomeFood)*.006-stress*.018));state.waterQuality=Math.max(0,Math.min(1,state.waterQuality+recovery*.8-(1-biomeWater)*.004-stress*.012));state.soilQuality=Math.max(0,Math.min(1,state.soilQuality+recovery*.7-stress*.008));state.lastUpdateDay=Number(world.day??state.lastUpdateDay);region.ecology=key;region.biome??=biome.type;}return world.spatial.ecology;}

export function updateSettlementState(world,agents=[]){normalizeSpatialWorld(world);const byRegion=new Map(),structures=[...(world.structures?.shelters??[]),...(world.structures?.farms??[])];for(const agent of agents??[]){if(!agent?.alive)continue;const key=getRegionKey(agent.position,world),entry=byRegion.get(key)??{population:0,structures:0};entry.population++;byRegion.set(key,entry);}for(const structure of structures){const position=structure.position;if(!position)continue;const key=getRegionKey(position,world),entry=byRegion.get(key)??{population:0,structures:0};entry.structures++;byRegion.set(key,entry);}for(const[key,state]of Object.entries(world.spatial.regions)){const live=byRegion.get(key)??{population:0,structures:0};state.population=live.population;state.structures=live.structures;state.settlementLevel=Math.min(5,Math.floor((live.population+live.structures)/2));state.activity=Math.min(1,live.population*.12+live.structures*.08);}for(const[key,live]of byRegion){const region=world.spatial.regions[key]??={key,visits:0,discovered:true};const pos=region.x!=null&&region.z!=null?{x:world.bounds.minX+Number(region.x)*world.spatial.regionSize+world.spatial.regionSize/2,z:world.bounds.minZ+Number(region.z)*world.spatial.regionSize+world.spatial.regionSize/2}:null;const biome=getBiomeForRegion(pos?getRegionForPosition(pos,world):getRegionForPosition({x:0,z:0},world),world);region.biome??=biome.type;region.population=live.population;region.structures=live.structures;region.settlementLevel=Math.min(5,Math.floor((live.population+live.structures)/2));region.activity=Math.min(1,live.population*.12+live.structures*.08);}return world.spatial.regions;}
